import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDIcwObBGNRu9HMmVImfL1Lg5TCJ2hZyo',
    appId: '1:59273264687:android:e72369fd95d8368d9090da',
    messagingSenderId: '59273264687',
    projectId: 'starter-flutter-template',
    storageBucket: 'starter-flutter-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHLW4STZie2JUvRmLgdJ-1I2RBkHCXhaE',
    appId: '1:59273264687:ios:e1f151d4821e43569090da',
    messagingSenderId: '59273264687',
    projectId: 'starter-flutter-template',
    storageBucket: 'starter-flutter-template.appspot.com',
    iosClientId:
        '59273264687-9178k937g5nhcmlnsqvolti7pvh3fjns.apps.googleusercontent.com',
    iosBundleId: 'com.example.starter',
  );
}
